[package]
name = "envfury"
version = "0.2.1"
edition = "2021"
license = "MIT"
description = "Utilities for procedural reading of the env varaibles."
repository = "https://github.com/MOZGIII/envfury.git"
keywords = ["env", "settings", "config"]

[dependencies]
thiserror = "2"
